#!/usr/bin/env python3
"""Generate reference/catalog.md — a grouped index of every charlib/scenes
helper with the first line of its docstring, plus an interest→helper map.

LLM skill users stop grepping a 4,000-line module: SKILL.md points here.
Deterministic output; re-run whenever helpers are added:

    python tools/gen_catalog.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "reference", "catalog.md")

INTERESTS = {
    "cars & trucks": "car_side pickup_truck school_bus dump_truck fire_truck "
                     "ambulance police_car tractor excavator",
    "trains": "train_engine train_car rail_track",
    "air": "airplane helicopter hot_air_balloon",
    "boats & water": "sailboat rowboat canoe whale_spout octopus fish duck "
                     "anchor waves pond beach_shore",
    "space": "rocket planet_ringed moon ufo satellite telescope shooting_star "
             "star_field crater_ground star sparkle",
    "flowers & garden": "flower tulip sunflower apple_tree potted_plant cactus "
                        "garden_strip tree_round tree_pine leaf",
    "wild animals": "lion elephant giraffe monkey owl frog turtle snail "
                    "rabbit bird_side horse butterfly",
    "farm": "barn cow sheep chicken pig horse baby_goat fence_ranch tractor",
    "pets": "dog dog_sit dog_sleep cat_sitting teddy food_bowl bone kibble",
    "games & toys": "kite scooter tricycle seesaw sandbox blocks dice drum "
                    "puzzle_piece ice_cream soccer_ball ball swing_set balloon",
    "buildings": "house village_house castle_small treehouse schoolhouse "
                 "lighthouse windmill barn tent fairy_door",
    "landscapes": "hill mountain mountain_range road rail_track fence_picket "
                  "fence_ranch pond beach_shore forest_border skyline bridge "
                  "ground_line",
    "people & poses": "kid_stand kid_run kid_jump kid_point kid_carry "
                      "kid_sitting kid_reach kid_toddler kid_wheelchair "
                      "kid_in_bed kids_holding_hands face face_traits",
    "creativity": "speech_bubble thought_bubble symmetry_page finish_page "
                  "pattern_menu design_template sticker_sheet",
    "letters & words": "letter word word_width banner name_trace_page "
                       "guideline otext",
    "line craft": "smooth_path limb wavy_line zigzag_line scallop_edge "
                  "stitch_dash hatch_region echo matted",
}


def parse_module(path):
    """Yield (section, [(name, first_docstring_line), ...]) in file order."""
    section = "helpers"
    groups = []
    with open(path) as fh:
        lines = fh.readlines()
    i = 0
    while i < len(lines):
        ln = lines[i]
        m = re.match(r"# -+ (.+)", ln.strip())
        if m:
            section = m.group(1).strip()
            i += 1
            continue
        m = re.match(r"^def (\w+)\(", ln)
        if m and not m.group(1).startswith("_"):
            name = m.group(1)
            doc = ""
            j = i + 1
            if j < len(lines) and lines[j].strip().startswith('"""'):
                doc = lines[j].strip().strip('"')
                if len(lines[j].strip()) == 3:  # multiline docstring
                    if j + 1 < len(lines):
                        doc = lines[j + 1].strip()
            groups.append((section, name, doc.splitlines()[0] if doc else ""))
        i += 1
    return groups


def main():
    charlib = parse_module(os.path.join(ROOT, "lib", "charlib.py"))
    scenes = parse_module(os.path.join(ROOT, "lib", "scenes.py"))
    photolib = parse_module(os.path.join(ROOT, "lib", "photolib.py"))

    out = ["# Helper catalog",
           "",
           "Auto-generated by `tools/gen_catalog.py` — re-run after adding",
           "helpers. Signatures live in `lib/charlib.py` / `lib/scenes.py`.",
           ""]
    out += ["## Find helpers by interest", ""]
    for interest, names in INTERESTS.items():
        out.append(f"- **{interest}**: `{names.replace(' ', '` `')}`")
    out.append("")

    out += ["## charlib", ""]
    last = None
    for section, name, doc in charlib:
        if section != last:
            out += [f"### {section}", ""]
            last = section
        doc = f" — {doc}" if doc else ""
        out.append(f"- `{name}`{doc}")
    out.append("")

    if scenes:
        out += ["## scenes (scene kits — composite backgrounds)", ""]
        for section, name, doc in scenes:
            doc = f" — {doc}" if doc else ""
            out.append(f"- `{name}`{doc}")
        out.append("")

    if photolib:
        out += ["## photolib (photo → coloring outline)", ""]
        for section, name, doc in photolib:
            doc = f" — {doc}" if doc else ""
            out.append(f"- `{name}`{doc}")
        out.append("")
    with open(OUT, "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote {OUT}: {len(charlib)} charlib helpers, {len(scenes)} scenes")


if __name__ == "__main__":
    main()
